### PR TITLE
(chore): Fixed nodejs version and add bower registry

### PR DESCRIPTION
**Pull request by duanhongyi**
Specify the version of node and the address of `bower register` to ensure the operation of example.

### CODE REVIEW

**Comment by Cryptophobia** [comment]
@duanhongyi , looks good! Thank you for changing and testing the example apps as well. Just the commit messages need to change to follow the style and we are good to merge after that! :+1:

**Comment by duanhongyi** [comment]
@Cryptophobia Hi hi, did you forget the merger?

**Comment by Cryptophobia** [comment]
> @Cryptophobia Hi hi, did you forget the merger?

@duanhongyi  I must have forgotten this one. Sorry about that. Just send me Slack messages for any PR that needs to be approved/tested/merged since sometimes with so many repos things slip through the cracks.

**Review by Cryptophobia — APPROVED** [review]
LGTM!

**Pull request merged**
